language: node_js
node_js:
- 12
dist: xenial
before_install:
- rvm install 2.2.2
before_script:
- npm install
- npm run test
notifications:
  slack:
    secure: biGEZX6gT90+dHZMBl7EQIbuIMzR8heoKyJJBno4Ex4oFIRd1ojkClUs2yl/1oM30FHniZsVJomaHwbUdC+8vzu2k0UKshaUqTtWISGQOrvohl+ajbPvRhQF4hNHFsPLmR0LU/2IApYo2Wpf8lm07zRwj7N434IuPJ2kz5BBBksx1ebrpunGnWXjpR33zeSgopS3GnShfc3mHpLhR9be1XVjjLnknti7fPypHrm4ZJXGgWatBaS2u2qHayPVuVkYJK0zqGdfz34PSPyiUgOcHEw9ng5fglo0hEHqEX2f9yJ14h+AjO0VRwzIlZGWIz84DducUdZnWE754d6mU0GSV8CfDs6gzxZGtpI3GB4Iwli1G4DhWKbUHpzDSwPi0rfpAfW2t+t1y6UbQ+sn0OvJVlhJx6TgcVHbZahMfcsgGu9AH/MWqB8zMeo0TRa3DMnJyIXsMUM3H4UX7VELOTErLvBryzdHPAmLvY63qmi3opwX6zsBY+JODNbtxRn0H7f/B1pjFDItKHSpcBhUeiVxLyiKw+J+3pSn2S38igI22K29AQGISwaNwwLRRW32aM9T6/qgBWjF74U8SRBAJRRG6y2HzNkdWaa+9u6rpsHUPegPP5VN1ziTOJOKrtLTDYysvmOEvTjWNJflHBayzXYbc2feVga47x3vbijL1XSLlSA=
